name: Request access to private bruker_pulseq repository
description: Request access to private bruker_pulseq repository
title: "Access request: <your-username>"
labels: ["request-access"]
body:
  - type: input
    id: username
    attributes:
      label: GitHub username
      description: Your GitHub handle (no @)
      placeholder: octocat
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Details (optional)
      description: Institution; bruker developer or user?
      placeholder: e.g., collaborator on project X
    validations:
      required: true
