name: Request access to private bruker_pulseq repository
description: Request access to private bruker_pulseq repository
title: "Access request: <your-username>"
labels: ["request-access"]
body:
  - type: input
    id: username
    attributes:
      label: GitHub username
      description: Your GitHub handle (no @)
      placeholder: octocat
    validations:
      required: true
  - type: textarea
    id: institution
    attributes:
      label: Institution
      placeholder: 
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Additional Details (optional)
      placeholder: e.g., pulseq users, sequence developer, etc...
    validations:
      required: false
